data:
  image_folder: data/train/images
  label_file_path: data/train.txt
  image_size: 384
  num_classes: 2
  batch_size: 8
  num_workers: 4
train:
  seed: 42
  epochs: 30
  loss_fn: crossentropy
  learning_rate: 0.0001
  optimizer: AdamW
  weight_decay: 1.0e-05
  momentum: 0.9
  patience: 3
  save_top_k: -1
  accelerator: gpu
  deviceid:
  - 6
  - 7
  lr_scheduler: cosineannealinglr
  lr_scheduler_step_size: 5
  lr_scheduler_gamma: 0.1
  lr_scheduler_mode: min
  lr_scheduler_patience: 3
  lr_scheduler_factor: 0.1
augment:
  random_horizontal_flip_p: 0.5
  random_vertical_flip_p: 0.0
  random_rotation_degrees: 15
  color_jitter_brightness: 0.2
  color_jitter_contrast: 0.2
  color_jitter_saturation: 0.2
  color_jitter_hue: 0.1
  random_erasing_p: 0.0
  gaussian_blur_p: 0.0
  sharpen_p: 0.0
  add_gaussian_noise_p: 0.0
  add_gaussian_noise_mean: 0.0
  add_gaussian_noise_std: 0.01
module:
  dataModule: utils/data_loader/dataloader.py
  modelModule: tl_models/models/effnetv2_xl.py
  tl_model_module: tl_models/tl_model.py
logging:
  log_dir: ./a_logs
  single_logname: effnetv2_xl
  experiment_name: fake_image_detection
